Repository thullo/thullo-backend, pull requests merged in 2023-04, with the labels that each got.

#65 THULLO-66: Implementation of Task Status from Enum to String
  src/main/java/com/thullo/ThulloApplication.java
  src/main/java/com/thullo/data/model/Status.java
  src/main/java/com/thullo/data/model/Task.java
  src/main/java/com/thullo/data/repository/TaskRepository.java
  src/main/java/com/thullo/service/BoardServiceImpl.java
  src/main/java/com/thullo/service/TaskService.java
  src/main/java/com/thullo/service/TaskServiceImpl.java
  src/main/java/com/thullo/util/Helper.java
  src/main/java/com/thullo/web/controller/BoardController.java
  src/main/java/com/thullo/web/controller/TaskController.java
  src/main/java/com/thullo/web/payload/request/TaskRequest.java
  src/main/java/com/thullo/web/payload/response/BoardResponse.java
  src/test/java/com/thullo/service/TaskServiceImplTest.java
Labels: documentation

#67 THULLO-100: Endpoint Implementation for Editing Task Status
  src/main/java/com/thullo/service/BoardServiceImpl.java
  src/main/java/com/thullo/service/TaskService.java
  src/main/java/com/thullo/service/TaskServiceImpl.java
  src/main/java/com/thullo/web/controller/TaskController.java
  src/main/java/com/thullo/web/payload/request/BoardRequest.java
  src/main/java/com/thullo/web/payload/request/StatusRequest.java
  src/test/java/com/thullo/service/AuthServiceImplTest.java
  src/test/java/com/thullo/service/BoardServiceImplTest.java
  src/test/java/com/thullo/service/TaskServiceImplTest.java
Labels: enhancement

#69 THULLO-116: Implement preview deployment in COR configuration to enable server resource access through the URL when the UI is deployed.
  src/main/resources/application.properties
Labels: documentation, enhancement

#68 THULLO-107: API Implementation to Delete Status
  src/main/java/com/thullo/service/TaskService.java
  src/main/java/com/thullo/service/TaskServiceImpl.java
  src/main/java/com/thullo/web/controller/TaskController.java
  src/test/java/com/thullo/service/TaskServiceImplTest.java
Labels: enhancement

#75 Thullo 118
  src/main/java/com/thullo/data/model/Board.java
  src/main/java/com/thullo/data/model/User.java
  src/main/java/com/thullo/data/repository/BoardRepository.java
  src/main/java/com/thullo/data/repository/UserRepository.java
  src/main/java/com/thullo/service/BoardService.java
  src/main/java/com/thullo/service/BoardServiceImpl.java
  src/main/java/com/thullo/service/TaskService.java
  src/main/java/com/thullo/service/TaskServiceImpl.java
  src/main/java/com/thullo/web/controller/BoardController.java
  src/main/java/com/thullo/web/controller/TaskController.java
  src/main/java/com/thullo/web/payload/request/PageLoadRequest.java
  src/test/java/com/thullo/service/BoardServiceImplTest.java
Labels: documentation

#76 Thullo 118
  src/main/java/com/thullo/security/CustomUserDetailService.java
  src/main/java/com/thullo/service/AuthService.java
  src/main/java/com/thullo/service/TaskService.java
  src/main/java/com/thullo/service/TaskServiceImpl.java
  src/main/java/com/thullo/web/controller/BoardController.java
  src/main/java/com/thullo/web/controller/TaskController.java
  src/main/java/com/thullo/web/payload/request/StatusRequest.java
  src/test/java/com/thullo/service/TaskServiceImplTest.java
Labels: enhancement
